### ISSUE TITLE
sls deploy 했을때 internal server error

### ISSUE THREAD

**Issue by Q00** [prography/book-recommend#28]
sls offline start했을 시에 문제 없이 실행되나 sls deploy후 안되는 문제

**Comment by Q00** [comment]
해당 문제는 webpack.config.js와 .babelrc에서 root 경로 설정(module.resolver)과
serverless.yml에 
```
custom:
  webpack:
    webpackConfig: ./webpack.config.js
  webpackIncludeModules: true
```
로 설정해주면 처리 가능하다.

cloudwatch log 에 stacktrace를 보며 해당 에러 찾았다.

참고 : [unable to import module in serverless-webpack](https://github.com/serverless-heaven/serverless-webpack/issues/43)
